services:
  - type: web
    name: dupr-feed
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 180 --workers 2 --worker-class gthread --threads 4
    envVars:
      - key: SECRET_KEY
        generateValue: true
