services:
  - type: web
    name: dupr-feed
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120 --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
